profile: dev
models:
  - model: ${AZURE_OPENAI_MODEL_NAME:gpt-4.1-nano}
    api_type: azure
    api_version: ${AZURE_OPENAI_API_VERSION:2024-12-01-preview}
    deployment: ${AZURE_OPENAI_DEPLOYMENT:gpt-4.1-nano}
logging:
  root_log_level: debug
  log_level: debug
chat_history:
  database_type: sqlite
  database_path: ./.tmp/high_level_logs.db
  database_name: ToDoList
  memory_path: ./.tmp
chat_service:
  type: multi_agent
tool_service:
  enable: false
azure_search_services:
  - service: default
    endpoint: ${AZURE_SEARCH_ENDPOINT:https://your-search-service.search.windows.net}
azure_sql_services:
  database_name: ${AZURE_SQL_DATABASE_NAME:dbo}
  table_name: ${AZURE_SQL_TABLE_NAME:sample_table}
web_configuration:
  type: fastapi
  ip_address: ${WEB_IP_ADDRESS:0.0.0.0}
  port: ${WEB_PORT:80}
  authentication:
    enable: ${WEB_AUTH_ENABLE:true}
    type: basic
chainlit_configuration:
  enable: false
prompt_tuner:
  mode: "fast_api"
local_sql_db:
  database_path: ${LOCAL_SQL_DB_PATH:/tmp/sample_sql.db}
  sample_csv_path: ${LOCAL_SQL_CSV_PATH:./ingenious/sample_dataset/cleaned_students_performance.csv}
  sample_database_name: ${LOCAL_SQL_DB_NAME:sample_data}
file_storage:
  revisions:
    enable: true
    storage_type: local
    container_name: jrsrevisions
    path: .files
    add_sub_folders: true
  data:
    enable: true
    storage_type: local
    container_name: jrsdata
    path: .files
    add_sub_folders: true
