# Profile Configuration
profile: dev # Defines the environment or profile for the deployment (e.g., dev, prod). NOTE this must match the profile in the profile.yml file
# Models Configuration
models:
  - model: ${AZURE_OPENAI_MODEL_NAME:gpt-4o} # Specifies the model being used (e.g., GPT-4 in Azure deployment)
    api_type: azure # API type indicates that the deployment is through Azure
    api_version: ${AZURE_OPENAI_API_VERSION:2024-08-01-preview} # API version being used in the deployment
    deployment: ${AZURE_OPENAI_DEPLOYMENT:gpt-4o} # Azure deployment name
# Logging Configuration
logging:
  root_log_level: debug # Root logging level for overall logging output (can be debug, info, warning, error)
  log_level: debug # Specific logging level for this application or service
# Chat History Configuration
chat_history:
  database_type: sqlite # Defines the type of database for storing chat history (e.g., sqlite or cosmos)
  database_path: ./.tmp/high_level_logs.db # Path to SQLite database file for storing chat logs (used only for SQLite)
  database_name: ToDoList # Name of the database (used only for Cosmos DB, irrelevant for SQLite)
  memory_path: ./.tmp # Location for temporary memory or cache files (used by chroma db)
# Chat Service Configuration
chat_service:
  type: multi_agent # Defines the type of chat service. Multi-agent implies multiple models or systems handling tasks
# Tool Service Configuration
tool_service:
  enable: false # Tool service is disabled in this configuration (set to 'true' to enable)
# Azure Search Services Configuration
azure_search_services:
  - service: default # Default Azure Search service configuration
    endpoint: ${AZURE_SEARCH_ENDPOINT:https://your-search-service.search.windows.net} # Azure Search endpoint for queries
# Azure SQL Services Configuration
azure_sql_services:
  database_name: ${AZURE_SQL_DATABASE_NAME:dbo}
  table_name: ${AZURE_SQL_TABLE_NAME:sample_table}
# Web Server Configuration
web_configuration:
  type: fastapi # Framework being used for web services (currently only FastAPI is supported)
  ip_address: ${WEB_IP_ADDRESS:0.0.0.0} # IP address where the web service will be hosted (0.0.0.0 allows all incoming connections)
  port: ${WEB_PORT:80} # Port on which the service is exposed
  # Authentication Configuration
  authentication:
    enable: ${WEB_AUTH_ENABLE:true} # Authentication method for securing the service (set to 'false' to disable)
    type: basic # Basic authentication type (can be expanded to other methods as needed)
# Chainlit Configuration
chainlit_configuration:
  enable: false
prompt_tuner:
  mode: "fast_api" # Mount in fast_api or stand alone flask (e.g., fast_api, flask)
# Local SQL Database Configuration
local_sql_db:
  database_path: ${LOCAL_SQL_DB_PATH:/tmp/sample_sql.db}
  sample_csv_path: ${LOCAL_SQL_CSV_PATH:./ingenious/sample_dataset/cleaned_students_performance.csv}
  sample_database_name: ${LOCAL_SQL_DB_NAME:sample_data}
# file storage configuration
file_storage:
  revisions:
    enable: true
    storage_type: local
    container_name: jrsrevisions
    path: .files
    add_sub_folders: true
  data:
    enable: true
    storage_type: local
    container_name: jrsdata
    path: .files
    add_sub_folders: true
