[project]
name = "insight-ingenious"
version = "0.1.0"
description = "GenAI Accelerator"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "annotated-types==0.7.0",
    "anyio>=4.9.0",
    "autogen-agentchat==0.5.7",
    "autogen-ext[openai]==0.5.7",
    "azure-core==1.34.0",
    "azure-cosmos>=4.9.0",
    "azure-identity>=1.17.1",
    "azure-keyvault>=4.2.0",
    "azure-search-documents==11.5.2",
    "azure-storage-blob>=12.25.1",
    "certifi==2025.4.26",
    "chainlit==2.5.5",
    "chromadb==1.0.11",
    "colorlog>=6.9.0",
    "duckdb==1.3.0",
    "fastapi==0.115.9",
    "fastapi-cli==0.0.7",
    "flask==3.1.1",
    "ipython==9.2.0",
    "jinja2==3.1.6",
    "jsonpickle==4.1.0",
    "markdown==3.8",
    "markdown-it-py==3.0.0",
    "markdownify==1.0.0",
    "markpickle==1.6.1",
    "matplotlib==3.10.3",
    "numpy==2.2.6",
    "openai==1.82.0",
    "pandas==2.2.3",
    "pydantic==2.11.5",
    "pyodbc==5.2.0",
    "pypdf==5.5.0",
    "seaborn==0.13.2",
    "typer>=0.15.4",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.14.0",
    "pytest-timeout>=2.4.0",
    "ruff>=0.11.10",
    "vulture>=2.14",
]

[project.optional-dependencies]
dataprep = [
    "scrapfly-sdk==0.8.23",
    "python-dotenv==1.0.1",
    "backoff==2.2"
]

tests = [
  "pytest==8.3.5",
  "pytest-asyncio==0.26.0",
  "pytest-timeout==2.4.0",
  "pytest-mock==3.14.0",
  "pytest-cov==6.1.1",
  "pre-commit==4.2.0",
  "ruff==0.11.10",
  "vulture==2.14",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["ingenious*", "ingenious_prompt_tuner*"]
exclude = ["tests*"]

[project.scripts]
ingen = "ingenious.cli:app"

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["E402"]

[tool.pytest.ini_options]
markers = [
    "e2e: live network integration test (requires SCRAPFLY_API_KEY)",
]
