profile: dev
models: 
  - model: gpt-4o
    api_type: azure      
    api_version: 2024-08-01-preview
logging: 
  root_log_level: debug
  log_level: debug
chat_history:  
  database_type: sqlite # cosmos or sqlite
  database_path: ./tmp/high_level_logs.db # only used for sqlite
  database_name: ToDoList # only used for cosmos
  memory_path: ./tmp
chainlit_configuration:
  enable: true
chat_service:
  type: multi_agent
tool_service:
  enable: false
local_sql_db:
  database_path: ./tmp/sample_sql.db
  sample_csv_path: ./ingenious/sample_dataset/cleaned_students_performance.csv
  sample_database_name: sample_data
azure_sql_services:
  database_name: skip #dbo or skip
  table_name: cleaned_students_performance
azure_search_services:
  - service: search-index-demo
    endpoint: https://search-index-demo.search.windows.net
web_configuration:
  type: fastapi #currently only fastapi is supported
  ip_address: "0.0.0.0"
  port: 80
  authentication: 
    enable: false # true or false
    type: basic # basic     