- name: dev
  models:
    - model: gpt-4-deployment        
      api_key: ######
      base_url: ######
  chat_history:        
    database_connection_string: AccountEndpoint=https://yourconnection; # only used for cosmos
  azure_search_services:
  - service: default
    key: # your key
  chainlit_configuration:
    enable: true
    authentication: 
      enable: true
      github_secret:  ###### 
      github_client_id:  ######
  web_configuration:
    authentication: 
      username:  # used for basic authentication
      password:  # used for basic authentication