- name: dev
  models:
    - model: gpt-4o
      api_key: #####
      base_url: #####
  chat_history:
    database_connection_string: #####
  azure_search_services:
  - service: search-index-demo
    key: #####
  azure_sql_services:
    database_connection_string: #####
  chainlit_configuration:
    enable: true
    authentication:
      enable: false
      github_secret: #####
      github_client_id: #####
  web_configuration:
    authentication:
      enable: false
      username:  "#####"
      password:  "#####"
