name: Security Checks
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run daily at 02:00 UTC
    - cron: '0 2 * * *'
jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run pip-audit vulnerability scan
        run: |
          uv run pip-audit --format=json --output=audit-results.json
          uv run pip-audit --format=table
        continue-on-error: true
      - name: Upload audit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: vulnerability-scan-results
          path: audit-results.json
          retention-days: 30
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install 3.13
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Check dependency compatibility
        run: uv pip check
      - name: Run dependency tree analysis
        run: uv tree --format=json > dependency-tree.json
      - name: Upload dependency analysis
        uses: actions/upload-artifact@v4
        with:
          name: dependency-analysis
          path: dependency-tree.json
          retention-days: 7
